In [1]:
import pandas as pd 
import numpy as np

In [28]:
df=pd.read_csv('audi.csv')
df.head()

model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0    A1  2017  12500       Manual    15735   Petrol  150  55.4         1.4
1    A6  2016  16500    Automatic    36203   Diesel   20  64.2         2.0
2    A1  2016  11000       Manual    29946   Petrol   30  55.4         1.4
3    A4  2017  16800    Automatic    25952   Diesel  145  67.3         2.0
4    A3  2019  17300       Manual     1998   Petrol  145  49.6         1.0

In [29]:
df.shape

(10668, 9)

In [8]:
df.dtypes

model            object
year              int64
price             int64
transmission     object
mileage           int64
fuelType         object
tax               int64
mpg             float64
engineSize      float64
dtype: object

In [9]:
df.isnull().sum()

model           0
year            0
price           0
transmission    0
mileage         0
fuelType        0
tax             0
mpg             0
engineSize      0
dtype: int64

In [10]:
df['model'].value_counts()

 A3     1929
 Q3     1417
 A4     1381
 A1     1347
 A5      882
 Q5      877
 Q2      822
 A6      748
 Q7      397
 TT      336
 A7      122
 A8      118
 Q8       69
 RS6      39
 RS3      33
 RS4      31
 RS5      29
 R8       28
 S3       18
 SQ5      16
 S4       12
 SQ7       8
 S8        4
 S5        3
 A2        1
 RS7       1
Name: model, dtype: int64

In [30]:
df['year'].value_counts()

2019    3197
2016    1964
2017    1935
2015     999
2018     864
2020     716
2014     447
2013     291
2012      85
2011      47
2010      32
2009      23
2008      21
2007      16
2006       9
2005       7
2003       6
2004       5
2002       2
1998       1
1997       1
Name: year, dtype: int64

In [13]:
df['transmission'].value_counts()

Manual       4369
Semi-Auto    3591
Automatic    2708
Name: transmission, dtype: int64

In [14]:
df['fuelType'].value_counts()

Diesel    5577
Petrol    5063
Hybrid      28
Name: fuelType, dtype: int64

#### Count frequency encoding to model & year column 

In [31]:
model_map=df['model'].value_counts().to_dict()

In [16]:
model_map

{' A3': 1929,
 ' Q3': 1417,
 ' A4': 1381,
 ' A1': 1347,
 ' A5': 882,
 ' Q5': 877,
 ' Q2': 822,
 ' A6': 748,
 ' Q7': 397,
 ' TT': 336,
 ' A7': 122,
 ' A8': 118,
 ' Q8': 69,
 ' RS6': 39,
 ' RS3': 33,
 ' RS4': 31,
 ' RS5': 29,
 ' R8': 28,
 ' S3': 18,
 ' SQ5': 16,
 ' S4': 12,
 ' SQ7': 8,
 ' S8': 4,
 ' S5': 3,
 ' A2': 1,
 ' RS7': 1}

In [32]:
df['model']=df['model'].map(model_map)
df.head()

model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0   1347  2017  12500       Manual    15735   Petrol  150  55.4         1.4
1    748  2016  16500    Automatic    36203   Diesel   20  64.2         2.0
2   1347  2016  11000       Manual    29946   Petrol   30  55.4         1.4
3   1381  2017  16800    Automatic    25952   Diesel  145  67.3         2.0
4   1929  2019  17300       Manual     1998   Petrol  145  49.6         1.0

In [33]:
year_map=df['year'].value_counts().to_dict()

In [34]:
df['year']=df['year'].map(year_map)

In [35]:
df.head()

model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0   1347  1935  12500       Manual    15735   Petrol  150  55.4         1.4
1    748  1964  16500    Automatic    36203   Diesel   20  64.2         2.0
2   1347  1964  11000       Manual    29946   Petrol   30  55.4         1.4
3   1381  1935  16800    Automatic    25952   Diesel  145  67.3         2.0
4   1929  3197  17300       Manual     1998   Petrol  145  49.6         1.0

#### One hot encoding to transmission & fuel type

In [38]:
df_transmission=pd.get_dummies(df[['transmission']],drop_first=True)

In [39]:
df_transmission.head()

transmission_Manual  transmission_Semi-Auto
0                    1                       0
1                    0                       0
2                    1                       0
3                    0                       0
4                    1                       0

In [40]:
df['transCat1']=df_transmission['transmission_Manual']

In [41]:
df['transCat2']=df_transmission['transmission_Semi-Auto']

In [42]:
df.head()

model  year  price transmission  mileage fuelType  tax   mpg  engineSize  \
0   1347  1935  12500       Manual    15735   Petrol  150  55.4         1.4   
1    748  1964  16500    Automatic    36203   Diesel   20  64.2         2.0   
2   1347  1964  11000       Manual    29946   Petrol   30  55.4         1.4   
3   1381  1935  16800    Automatic    25952   Diesel  145  67.3         2.0   
4   1929  3197  17300       Manual     1998   Petrol  145  49.6         1.0   

   transCat1  transCat2  
0          1          0  
1          0          0  
2          1          0  
3          0          0  
4          1          0

In [45]:
df_fuel=pd.get_dummies(df[['fuelType']],drop_first=True)

In [46]:
df_fuel.head()

fuelType_Hybrid  fuelType_Petrol
0                0                1
1                0                0
2                0                1
3                0                0
4                0                1

In [47]:
df['fuelCat1']=df_fuel['fuelType_Petrol']

In [48]:
df['fuelCat2']=df_fuel['fuelType_Hybrid']

In [49]:
df.head()

model  year  price transmission  mileage fuelType  tax   mpg  engineSize  \
0   1347  1935  12500       Manual    15735   Petrol  150  55.4         1.4   
1    748  1964  16500    Automatic    36203   Diesel   20  64.2         2.0   
2   1347  1964  11000       Manual    29946   Petrol   30  55.4         1.4   
3   1381  1935  16800    Automatic    25952   Diesel  145  67.3         2.0   
4   1929  3197  17300       Manual     1998   Petrol  145  49.6         1.0   

   transCat1  transCat2  fuelCat1  fuelCat2  
0          1          0         1         0  
1          0          0         0         0  
2          1          0         1         0  
3          0          0         0         0  
4          1          0         1         0

In [50]:
features=['model','year','mileage','tax','mpg','engineSize','transCat1','transCat2','fuelCat1','fuelCat2']

In [54]:
X=df[features]
X=np.asarray(X)
X[:5]

array([[1.3470e+03, 1.9350e+03, 1.5735e+04, 1.5000e+02, 5.5400e+01,
        1.4000e+00, 1.0000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00],
       [7.4800e+02, 1.9640e+03, 3.6203e+04, 2.0000e+01, 6.4200e+01,
        2.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
       [1.3470e+03, 1.9640e+03, 2.9946e+04, 3.0000e+01, 5.5400e+01,
        1.4000e+00, 1.0000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00],
       [1.3810e+03, 1.9350e+03, 2.5952e+04, 1.4500e+02, 6.7300e+01,
        2.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
       [1.9290e+03, 3.1970e+03, 1.9980e+03, 1.4500e+02, 4.9600e+01,
        1.0000e+00, 1.0000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00]])

In [56]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X= sc.fit_transform(X)
print(X)

[[ 0.3347124   0.02496191 -0.3868356  ... -0.71233307  1.05216498
  -0.05129892]
 [-0.83599999  0.0539149   0.48398914 ... -0.71233307 -0.95042129
  -0.05129892]
 [ 0.3347124   0.0539149   0.21778089 ... -0.71233307  1.05216498
  -0.05129892]
 ...
 [ 1.47219922 -1.19206202 -1.03038137 ... -0.71233307  1.05216498
  -0.05129892]
 [ 0.47152353  0.02496191 -0.68844184 ... -0.71233307  1.05216498
  -0.05129892]
 [ 0.47152353  0.0539149  -0.55191279 ... -0.71233307  1.05216498
  -0.05129892]]


In [57]:
Y=df['price']
Y=np.asarray(Y)
Y[:5]

array([12500, 16500, 11000, 16800, 17300], dtype=int64)

In [58]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

In [59]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(8534, 10)
(8534,)
(2134, 10)
(2134,)


In [60]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression() 
regressor.fit(x_train, y_train)

LinearRegression()

In [62]:
yhat_LR=regressor.predict(x_test)
yhat_LR

array([13698.47818842, 28687.71683747, 32179.91359925, ...,
       43610.1504118 , 31581.13352929, 10995.10164751])

In [66]:
from sklearn.metrics import r2_score
print(r2_score(y_test,yhat_LR))

0.7714158094552397
